<a href="https://colab.research.google.com/github/Chandigarh-University-students/Devanagri-Text-Classifier/blob/main/Devanagri2_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive

In [2]:
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
import numpy as np
import os

In [4]:
from PIL import Image


In [5]:
IMG_WIDTH=32
IMG_HEIGHT=32


In [10]:
def create_dataset_PIL(img_folder):
    
    img_data_array=[]
    class_name=[]
    for dir1 in os.listdir(img_folder):
        for file in os.listdir(os.path.join(img_folder, dir1)):       
            image_path= os.path.join(img_folder, dir1,  file)
            image= np.array(Image.open(image_path))
            image= np.resize(image,(IMG_HEIGHT,IMG_WIDTH,3))
            image = image.astype('float32')
            image /= 255  
            img_data_array.append(image)
            class_name.append(dir1)
    return img_data_array , class_name

In [7]:
img_train_folder = '/content/drive/MyDrive/Devanagri dataset/DevanagariHandwrittenCharacterDataset/Train'

In [11]:
PIL_train_img_data, train_class_name=create_dataset_PIL(img_train_folder)


In [19]:
print(PIL_train_img_data[0])

[[[0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  ...
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]]

 [[0.         0.         0.        ]
  [0.         0.02745098 0.09019608]
  [0.03529412 0.         0.        ]
  ...
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]]

 [[0.         0.         0.18039216]
  [0.8862745  1.         0.7647059 ]
  [0.09019608 0.         0.        ]
  ...
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]]

 ...

 [[0.         0.         0.        ]
  [0.         0.         0.1764706 ]
  [0.9411765  1.         0.99607843]
  ...
  [1.         0.99607843 0.89411765]
  [0.7137255  0.4392157  0.15294118]
  [0.02745098 0.         0.        ]]

 [[0.         0.         0.        ]
  [0.         0.         0.        ]
