<a href="https://colab.research.google.com/github/Chandigarh-University-students/Devanagri-Classifier/blob/main/LoadDataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive

In [2]:
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
import pandas as pd


In [11]:
import pandas as pd
import numpy as np
import os
import tensorflow as tf
import cv2
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.layers import Dense, Input, InputLayer, Flatten
from tensorflow.keras.models import Sequential, Model
from  matplotlib import pyplot as plt
import matplotlib.image as mpimg
%matplotlib inline

In [6]:
pip install tensorflow 

In [7]:
pip install tensorflow.keras


ERROR: Could not find a version that satisfies the requirement tensorflow.keras (from versions: none)
ERROR: No matching distribution found for tensorflow.keras


In [57]:
def create_dataset_PIL(img_folder):
    
    img_data_array=[]
    class_name=[]
    for dir1 in os.listdir(img_folder):
        print(dir1)
        for file in os.listdir(os.path.join(img_folder, dir1)):       
            image_path= os.path.join(img_folder, dir1,  file)
            image= np.array(Image.open(image_path))
            image= np.resize(image,(IMG_HEIGHT,IMG_WIDTH,3))
            image = image.astype('float32')
            image /= 255  
            img_data_array.append(image)
            class_name.append(dir1)
    return img_data_array , class_name

In [56]:
img_train_folder = '/content/DevanagariHandwrittenCharacterDataset/Train'

In [58]:
PIL_train_img_data, train_class_name=create_dataset_PIL(img_train_folder)

character_14_dhaa
digit_3
digit_2
character_20_na
character_36_gya
character_31_petchiryakha
digit_7
character_25_ma
character_30_motosaw
character_26_yaw
character_24_bha
character_1_ka
character_23_ba
character_33_ha
character_16_tabala
digit_4
character_35_tra
digit_9
character_34_chhya
character_2_kha
character_29_waw
digit_5
character_21_pa
digit_6
character_27_ra
digit_1
character_22_pha
character_6_cha
character_13_daa
character_10_yna
character_19_dha
character_32_patalosaw
digit_0
character_4_gha
character_5_kna
character_11_taamatar
character_18_da
character_9_jha
character_17_tha
character_7_chha
character_28_la
character_3_ga
digit_8
character_15_adna
character_12_thaa
character_8_ja


In [16]:
from PIL import Image


In [18]:
IMG_WIDTH=32
IMG_HEIGHT=32

In [22]:
import os
os.environ['KAGGLE_CONFIG_DIR'] = '/content'

In [24]:
!kaggle datasets download -d ujjawalsharma20/hindi-letters


 78% 59.0M/76.1M [00:00<00:00, 78.0MB/s]
100% 76.1M/76.1M [00:00<00:00, 111MB/s] 


In [32]:
!unzip '/content/hindi-letters.zip' -d '/content'

Streaming output truncated to the last 5000 lines.
  inflating: /content/DevanagariHandwrittenCharacterDataset/Train/digit_7/10299.png  
  inflating: /content/DevanagariHandwrittenCharacterDataset/Train/digit_7/10300.png  
  inflating: /content/DevanagariHandwrittenCharacterDataset/Train/digit_7/10301.png  
  inflating: /content/DevanagariHandwrittenCharacterDataset/Train/digit_7/10302.png  
  inflating: /content/DevanagariHandwrittenCharacterDataset/Train/digit_7/10303.png  
  inflating: /content/DevanagariHandwrittenCharacterDataset/Train/digit_7/10304.png  
  inflating: /content/DevanagariHandwrittenCharacterDataset/Train/digit_7/10306.png  
  inflating: /content/DevanagariHandwrittenCharacterDataset/Train/digit_7/10307.png  
  inflating: /content/DevanagariHandwrittenCharacterDataset/Train/digit_7/104017.png  
  inflating: /content/DevanagariHandwrittenCharacterDataset/Train/digit_7/104018.png  
  inflating: /content/DevanagariHandwrittenCharacterDataset/Train/digit_7/104019.png  


In [30]:
path_to_file = '/content/hindi-letters.zip'
path_to_directory = '/content'

In [34]:
img_data_array=[]
count=5
dir1 = '/content/DevanagariHandwrittenCharacterDataset/Train/character_10_yna'
class_name=dir1 
for file in os.listdir(os.path.join(img_folder, dir1)):
  image_path= os.path.join(img_folder, dir1,  file)
  image= np.array(Image.open(image_path))
  image= np.resize(image,(IMG_HEIGHT,IMG_WIDTH,3))
  image = image.astype('float32')
  image /= 255  
  img_data_array.append(image)

In [35]:
print(img_data_array)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [ ]:
print(img_data_array[1:5])

In [40]:
print(PIL_train_img_data[1])

[[[0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  ...
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]]

 [[0.         0.         0.79607844]
  [0.8901961  0.39607844 0.01568628]
  [0.         0.         0.        ]
  ...
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]]

 [[0.         0.         1.        ]
  [1.         0.63529414 0.02745098]
  [0.         0.         0.        ]
  ...
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]]

 ...

 [[0.         0.         0.        ]
  [0.00392157 0.35686275 0.99607843]
  [1.         0.8039216  0.5647059 ]
  ...
  [0.19607843 0.13333334 0.09411765]
  [0.05098039 0.03921569 0.03921569]
  [0.03137255 0.         0.        ]]

 [[0.         0.         0.        ]
  [0.00784314 0.45882353 1.        ]


In [41]:
type(PIL_train_img_data)

list

In [59]:
dim1 = len(PIL_train_img_data)
dim2 = len(PIL_train_img_data[0])
dim3 = len(PIL_train_img_data[0][0])


In [60]:
dim1


78200

In [62]:
dim2


32

In [63]:
dim3

32

In [64]:
dim4 = len(PIL_train_img_data[0][0][0])

In [65]:
dim4


3

In [48]:
dim4 = len(PIL_train_img_data[0][0][0][0])

TypeError: ignored

In [49]:
print(PIL_train_img_data[0][0][0])

[0. 0. 0.]


In [50]:
print(PIL_train_img_data.shape)

AttributeError: ignored

In [51]:
len(train_class_name)

7518

In [52]:
print(train_class_name[0])

digit_5


In [53]:
print(train_class_name[1:100])

['digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5', 'digit_5'

In [54]:
print(train_class_name[7000])

digit_6


In [55]:
print(train_class_name[3000])

digit_7
